# Generated by Django 4.2.4 on 2023-09-06 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_authors",
                to="api.contributor",
                verbose_name="comment author",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="api.issue",
                verbose_name="related issue",
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="project",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_contributors",
                to="api.project",
                verbose_name="project",
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("A", "Author"), ("CO", "Contributor")],
                max_length=2,
                verbose_name="contributor role",
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("P", "Project"), ("I", "Issue"), ("C", "Comment")],
                max_length=1,
                verbose_name="contributor type",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="author",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_authors",
                to="api.contributor",
                verbose_name="issue author",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="api.project",
                verbose_name="related project",
            ),
        ),
    ]
