# Generated by Django 4.2.5 on 2023-10-30 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="project",
        ),
        migrations.AlterField(
            model_name="project",
            name="contributors",
            field=models.ManyToManyField(
                blank=True,
                related_name="project_contributors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="project contributors",
            ),
        ),
    ]
