# Generated by Django 4.2.4 on 2023-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_contributor_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="issue_url",
            field=models.URLField(blank=True, verbose_name="url verse an issue"),
        ),
    ]
