# Generated by Django 4.2.4 on 2023-09-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_contributor_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_contributors",
                to="api.contributor",
                verbose_name="issue assigned to",
            ),
        ),
    ]
